// File generated by FlutterFire CLI — PLACEHOLDER.
//
// THIS FILE IS A DEMO PLACEHOLDER. It does NOT contain a real Firebase
// project. The values are deliberately empty so that `Firebase.initializeApp`
// throws a clean error on a real device, which our `lib/backend/firebase.dart`
// catches and turns into "local-only mode" (the app keeps working offline).
//
// To wire up a real Firebase project for this app:
//
//   1. Create a Firebase project in the Firebase console:
//      https://console.firebase.google.com/
//
//   2. In the project, enable **Cloud Firestore** (Native mode) and
//      **Firebase Storage**.
//
//   3. Install the FlutterFire CLI:
//        dart pub global activate flutterfire_cli
//
//   4. From the repository root, run:
//        flutterfire configure --project=<your-firebase-project-id>
//      This will OVERWRITE this file with a real, per-platform config
//      (Android, iOS, web, macOS, Windows) pulled from your Firebase
//      project. The generated file is the canonical one to check in.
//
//   5. In the Firebase console, configure server-side TTL for the four
//      collections documented in `docs/firestore-schema.md`. See the
//      "Firestore TTL policy" section of the README.
//
// Until you complete step 4, this placeholder keeps the build green and the
// app starts cleanly in offline-only mode.

import 'package:firebase_core/firebase_core.dart';

/// Default Firebase options for the platforms this app supports.
///
/// The values below are intentionally invalid placeholders. The FlutterFire
/// CLI generates real platform configs (different Android/iOS app ids,
/// different API keys, etc.) when you run `flutterfire configure` against a
/// real Firebase project. See the header comment above for the full setup.
class DefaultFirebaseOptions {
  static const FirebaseOptions currentPlatform = FirebaseOptions(
    apiKey: 'DEMO-API-KEY-REPLACE-WITH-FLUTTERFIRE-CONFIGURE',
    appId: 'DEMO-APP-ID-REPLACE-WITH-FLUTTERFIRE-CONFIGURE',
    messagingSenderId: 'DEMO-SENDER-ID',
    projectId: 'demo-relaylink',
    storageBucket: 'demo-relaylink.appspot.com',
  );
}
